### ISSUE TITLE
Return statements in a function

### ISSUE THREAD

**Issue by JQuinnie** [iAmWillShepherd/ama#3] opened 2018-01-13 23:44 UTC
When testing with a try/catch of a simple multiplication function, return does not return what I would expect... see code snippet.

```js
var assertThrows = function(func, x, y) {
  var threw = false;
  try {
    func(x, y);
  } catch(error) {
    var threw = true;
  }
  return threw;
};

var multiply = function(x, y) {
  if (typeof x !== 'number' || typeof y !== 'number') {
    throw new Error('one or both variable(s) is(are) not a number')
  }
  else {
    return x * y; // why didnt return actually return 8?
  }
};

console.log('2 * 4: Error is ' + assertThrows(multiply, 2, 4));
```

Specifically, the return statement did not return x * y in the multiply function. The code returns true/false based on the try/catch in the first part of the function (return threw). The only time I can return x*y = 8 is if I console.log it.

```js
  else {
     console.log(x * y);
    return x * y;
  }
```

**Comment by iAmWillShepherd** [comment] 2018-01-14 18:24
`multiply` behaves as expected: it returns _x_ multiplied by _y_.

Looks like `assertThrows` returns a boolean, not a number. Look closely and you will see that you call the `func` argument, but you don't capture its result anywhere into a variable or constant.

There is also something weird going on in your catch block. You are redeclaring the threw variable instead of reassigning to the one that existed already. It still works as intended, but that line should be a reassignment.

Does the boolean result make sense now?

**Closed** 2018-01-18 15:18 UTC
